### ISSUE TITLE
A progress bar

### ISSUE THREAD

**Issue by WatershedFlow** [hzambran/hydroPSO#17]
It might be convenient to include a progress bar to tell the progress. For example I have 10,000 calibration runs, it goes for several days with my current laptop. Built-in progress bar would be a nice to have.

**Comment by hzambran** [comment]
You might use the `REPORT` argument (only if `verbose=TRUE`) to see the progress of hydroPSO.

The default value of `REPORT` is 100, which might be too high if you use a large number of particles. 
``` 
hydroPSO( fn=rastrigin, lower=lower, upper=upper,        
               control=list(reltol=1e-20, REPORT=2, write2disk=FALSE) )
```
