### ISSUE TITLE
Questions about parallel with hydroPSO

### ISSUE THREAD

**Issue by WatershedFlow** [hzambran/hydroPSO#22]
Hi Mauricio,

I would like to use parallel function with hydroPSO. I think our machine here is Window based. I read your instruction, it seems that there are not many examples to show how to use such function, or maybe I just missed that part. Please provide some examples on how to use parallel in Window based machine.
Thanks so much
Kangsheng

**Comment by hzambran** [comment]
You're right, I don't use Windows anymore so I'm not able to test the functions of the hydroPSO package in a Windows machine. 

However, I have fixed all the issues reported by some Windows users.

Did you read Section 9 (Pag 93) in the [hydroPSO vignette](https://www.rforge.net/hydroPSO/files/hydroPSO_vignette.pdf) for SWAT2005 and MODFLOW2005 ?

**Comment by WatershedFlow** [comment]
Thanks so much, Mauricio,
I did it later on and fixed that by following your example. Just three
lines, it works perfectly. we have a HPC so that I can run with 15 or 20
cores, it is very fast.

Kangheng

**Comment by hzambran** [comment]
Perfect !. Thanks for confirming.
