### ISSUE TITLE
conda error

### ISSUE THREAD

**Issue by mforoughifar** [hzambran/hydroPSO#31]
I cannot install hydropso package using conda. Please let me know how I should proceed (I was able to install it on my own computer directly through rstudio using install.packages("hydropso") but I wasn't able to install it on a linux virtual environment on the university server using conda.)

**Comment by hzambran** [comment]
I'm not a conda user. If you are able to install the package in R on your own computer and then you are not able to install it by using conda, then is a conda issue. Please contact the conda developer(s)
