### ISSUE TITLE
Issue with parallel run

### ISSUE THREAD

**Issue by azzaea** [hzambran/hydroPSO#5]
The 'multicore' core package is no longer maintained by CRAN, and all its functionality is inherited in the 'parallel' package:
setting the control=list(parallel='multicore') in the function call yields the warning:
[ Package 'multicore' is not installed =>  parallel='none' ]

To still be able to use this functionality though, simply setting control=list(parallel='parallel') calls the right package

**Comment by hzambran** [comment]
> To still be able to use this functionality though, simply setting control=list(parallel='parallel') calls the right package

You're right. 
The `multicore` option is just maintained within the package for backward compatibility (old scripts running with the `multicore` option), even if the `multicore` package is superseded by the **parallel** package. Setting `control=list(parallel='parallel')` will work in most of the architectures.
